### ISSUE TITLE
# of comments not accurate

### ISSUE THREAD

**Issue by jerath** [elsieC/shiny-ironman#63]
Only counts top level comments and is not representative of the depth of conversation... it would be cool to see the count of all comments and replies!

**Comment by elschan** [comment]
I think that recursively querying might not be the best way to go about search through each nested comment since they're not assigned to the post. maybe i want to include a total comments column in posts and increment/decrement accordingly

Another thing was assigning the post id to those comments which works too for getting the count but didn't figure out how to display the comments onthe post (right now it's @post.comments so  they'd all show unnested as well.

**Comment by jerath** [comment]
Right. I totally tried the post id thing too. Lol bad time.

**Comment by elschan** [comment]
added column closing issue
